package org.example;// Generated by Selenium IDE

import org.junit.After;
import org.junit.Before;
import org.junit.Test;
import org.openqa.selenium.*;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.Select;
import org.openqa.selenium.support.ui.WebDriverWait;

import java.time.Duration;
import java.util.HashMap;
import java.util.Map;


public class a101webtest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    System.setProperty("webdriver.chrome.driver", "drivers\\chromedriver.exe");
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();

  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void waittest() {
    driver.get("https://www.a101.com.tr/");
    driver.manage().window().maximize();
    driver.findElement(By.id("CybotCookiebotDialogBodyLevelButtonLevelOptinAllowAll")).click();
    driver.findElement(By.cssSelector(".desktop-menu > .js-navigation-item:nth-child(4) > a")).click();
    WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(10));
    wait.until(ExpectedConditions.visibilityOfElementLocated(By.linkText("Kadın İç Giyim")));
    driver.findElement(By.linkText("Kadın İç Giyim")).click();
    wait.until(ExpectedConditions.visibilityOfElementLocated(By.linkText("Dizaltı Çorap")));
    driver.findElement(By.linkText("Dizaltı Çorap")).click();
    wait.until(ExpectedConditions.presenceOfElementLocated(By.id("attributes_integration_colourSİYAH")));
    WebElement child = driver.findElement(By.id("attributes_integration_colourSİYAH"));
    WebElement label = child.findElement(By.xpath("following-sibling::*[1]"));
    label.click();
    wait.until(ExpectedConditions.elementToBeClickable(By.cssSelector("a[href='/giyim-aksesuar/penti-kadin-50-denye-pantolon-corabi-siyah/']")));
    driver.findElement(By.cssSelector("a[href='/giyim-aksesuar/penti-kadin-50-denye-pantolon-corabi-siyah/']")).click();
    wait.until(ExpectedConditions.elementToBeClickable(By.cssSelector(".add-to-basket")));
    driver.findElement(By.cssSelector(".add-to-basket")).click();
    wait.until(ExpectedConditions.elementToBeClickable(By.linkText("Sepeti Onayla")));
    driver.findElement(By.linkText("Sepeti Onayla")).click();
    wait.until(ExpectedConditions.elementToBeClickable(By.linkText("ÜYE OLMADAN DEVAM ET")));
    driver.findElement(By.linkText("ÜYE OLMADAN DEVAM ET")).click();
    wait.until(ExpectedConditions.elementToBeClickable(By.name("user_email")));
    driver.findElement(By.name("user_email")).click();
    driver.findElement(By.name("user_email")).sendKeys("firav65270@keyido.com");
    wait.until(ExpectedConditions.elementToBeClickable(By.cssSelector(".button:nth-child(3)")));
    driver.findElement(By.cssSelector(".button:nth-child(3)")).click();

    wait.until(ExpectedConditions.elementToBeClickable(By.linkText("Yeni adres oluştur")));
    driver.findElement(By.linkText("Yeni adres oluştur")).click();

    wait.until(ExpectedConditions.elementToBeClickable(By.name("title")));
    driver.findElement(By.name("title")).click();
    driver.findElement(By.name("title")).sendKeys("adres");

    wait.until(ExpectedConditions.visibilityOfElementLocated(By.name("first_name")));
    driver.findElement(By.name("first_name")).sendKeys("ad");

    wait.until(ExpectedConditions.visibilityOfElementLocated(By.name("last_name")));
    driver.findElement(By.name("last_name")).sendKeys("soyad");

    wait.until(ExpectedConditions.visibilityOfElementLocated(By.name("phone_number")));
    driver.findElement(By.name("phone_number")).sendKeys("5555555555");

    wait.until(ExpectedConditions.elementToBeClickable(By.name("city")));
    Select dropdown = new Select(driver.findElement(By.name("city")));
    dropdown.selectByValue("40");

    wait.until(ExpectedConditions.elementToBeClickable(By.xpath("//*[@id=\"js-orders-modal-container\"]/div/div[2]/form/div[5]/div[2]/div/label/div/select/option[2]")));
    driver.findElement(By.xpath("//*[@id=\"js-orders-modal-container\"]/div/div[2]/form/div[5]/div[2]/div/label/div/select/option[2]")).click();

    wait.until(ExpectedConditions.elementToBeClickable(By.xpath("//*[@id=\"js-orders-modal-container\"]/div/div[2]/form/div[6]/label/div/select/option[2]")));
    driver.findElement(By.xpath("//*[@id=\"js-orders-modal-container\"]/div/div[2]/form/div[6]/label/div/select/option[2]")).click();

    vars.put("myRandomNumber", js.executeScript("return Math.random()"));
    driver.findElement(By.name("line")).sendKeys(vars.get("myRandomNumber").toString());
    driver.findElement(By.cssSelector(".js-set-country")).click();

    wait.until(ExpectedConditions.elementToBeClickable(By.xpath("/html/body/section/section/div/div[2]/div/div[1]/div/div[2]/form/div[2]/div[2]/ul/li[1]/label")));
    driver.findElement(By.xpath("/html/body/section/section/div/div[2]/div/div[1]/div/div[2]/form/div[2]/div[2]/ul/li[1]/label")).click();

    wait.until(ExpectedConditions.elementToBeClickable(By.xpath("/html/body/section/section/div/div[2]/div/div[1]/div/div[2]/form/div[2]/button")));
    driver.findElement(By.xpath("/html/body/section/section/div/div[2]/div/div[1]/div/div[2]/form/div[2]/button")).click();

    wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath("/html/body/section/section/div/div[3]")));

    driver.quit();

    System.out.println("Ödeme Ekranına ulaşıldı. Test Başarılı!");

  }
}
